### ISSUE TITLE
Missing Block at broadband_scan.grc

### ISSUE THREAD

**Issue by cloudlakecho** [ThomasHabets/radiostuff#3]
I try to run "broadband_scan.grc" and it looks like one block is missing. The block ID is the habets39_sweepsinkv_0. Where could I find the block in your repository? Or should I compile the `sweepsinkv_impl.cc` code at  the "gr-habets38/lib/" and connected to the block? 

Here is the screenshot of my GNURadio error window (red block is the missing one): 
![broadband_scan error](https://user-images.githubusercontent.com/12093406/135674166-2315b46b-f9f3-405b-897f-89961a4b1b48.png)

Runtime environment:  
&nbsp;&nbsp; OS: Ubuntu 18.04
&nbsp;&nbsp; GNURadio: 3.8.2.0
&nbsp;&nbsp; USRP model: X300

Thanks.

**Comment by ThomasHabets** [comment]
Sorry for the delay on this. A health thing took me out of effective commission for a few weeks.

For the flowgraph to work yes you need to build the modules from [this repo](https://github.com/ThomasHabets/gr-habets38). Hopefully should be as simple as:

```
cd habets38
mkdir build
cd build
cmake ..
make
sudo make install
```

Depending on how you have gnuradio installed, that should make my blocks appear in gnuradio-companion.

**Comment by cloudlakecho** [comment]
@ThomasHabets Oh, I hope that you are fully recovered. 
Thanks for the information of the prerequisite. 
My task was in a my company project, and the project was actually diverted to a different direction meanwhile. I will close this issue with your answer.
